### ISSUE TITLE
Doesn't run (maybe gtk?)

### ISSUE THREAD

**Issue by feja111** [Jazzzny/iFR#1]
This application does not start:

```
jakob@jax1yoga:~/Downloads/esp32-serial-bios/iFR$ python3.9 iFR.py 

(iFR.py:461975): Gtk-WARNING **: 19:16:49.522: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(iFR.py:461975): Gtk-WARNING **: 19:16:49.533: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)

(iFR.py:461975): Gtk-CRITICAL **: 19:16:49.533: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Traceback (most recent call last):
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 452, in <module>
    iFR(None, title='iFR')
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 371, in __init__
    self.InitUI()
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 424, in InitUI
    self.PopulateAvailableProgrammers()
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 429, in PopulateAvailableProgrammers
    options_start = output_lines.index(b'Valid choices are:\n')
ValueError: b'Valid choices are:\n' is not in list
```

My Enviroment:
```
jakob@jax1yoga:~/Downloads/esp32-serial-bios/iFR$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
jakob@jax1yoga:~/Downloads/esp32-serial-bios/iFR$ python3.9 --version
Python 3.9.2
```

**Comment by Jazzzny** [comment]
Can you run `flashrom` and post the output? Thanks.

**Comment by EmilEmilchen** [comment]
Hi there, I'm having the same issue:

    ➜  iFR git:(main) python iFR.py
    Traceback (most recent call last):
    File "/home/emil/Desktop/BIOSUpdate/iFR/iFR.py", line 452, in <module>
        iFR(None, title='iFR')
    File "/home/emil/Desktop/BIOSUpdate/iFR/iFR.py", line 371, in __init__
        self.InitUI()
    File "/home/emil/Desktop/BIOSUpdate/iFR/iFR.py", line 424, in InitUI
        self.PopulateAvailableProgrammers()
    File "/home/emil/Desktop/BIOSUpdate/iFR/iFR.py", line 429, in PopulateAvailableProgrammers
        options_start = output_lines.index(b'Valid choices are:\n')
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ValueError: b'Valid choices are:\n' is not in list

Heres the output when running `flashrom`:


    ➜  iFR git:(main) flashrom
    flashrom unknown on Linux 6.8.0-36-generic (x86_64)
    flashrom is free software, get the source code at https://flashrom.org

    Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
    Please select a programmer with the --programmer parameter.
    To choose the mainboard of this computer use 'internal'. Valid choices are:
    internal, dummy, nic3com, nicrealtek, gfxnvidia, raiden_debug_spi, drkaiser,
    satasii, atavia, it8212, ft2232_spi, serprog, buspirate_spi, dediprog,
    developerbox, rayer_spi, pony_spi, nicintel, nicintel_spi, nicintel_eeprom,
    ogp_spi, satamv, linux_mtd, linux_spi, usbblaster_spi, pickit2_spi, ch341a_spi,
    digilent_spi, stlinkv3_spi, dirtyjtag_spi.

**Comment by feja111** [comment]
> Can you run `flashrom` and post the output? Thanks.
Thank you for your fast reply.

```jakob@jax1yoga:~/Downloads/esp32-serial-bios/iFR$ ./flashrom 
flashrom v1.2 on Linux 5.10.0-30-amd64 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Please select a programmer with the --programmer parameter.
To choose the mainboard of this computer use 'internal'. Valid choices are:
internal, dummy, nic3com, nicrealtek, gfxnvidia, drkaiser, satasii, atavia,
it8212, ft2232_spi, serprog, buspirate_spi, dediprog, developerbox, rayer_spi,
pony_spi, nicintel, nicintel_spi, nicintel_eeprom, ogp_spi, satamv, linux_mtd,
linux_spi, usbblaster_spi, pickit2_spi, ch341a_spi, digilent_spi, stlinkv3_spi.
```

**Comment by feja111** [comment]
He is using wayland. I am using the classic x11.

**Comment by Jazzzny** [comment]
I see the problem now, please try the new commit. Thanks

**Comment by feja111** [comment]
I am afraid the problem kind of persists with a different gtk stack trace.

```
jakob@jax1yoga:~/Downloads/esp32-serial-bios/iFR$ python3.9 iFR.py

(iFR.py:519771): Gtk-WARNING **: 20:20:43.043: Negative content height -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(iFR.py:519771): Gtk-WARNING **: 20:20:43.053: Negative content height -9 (allocation 1, extents 5x5) while allocating gadget (node scrollbar, owner GtkScrollbar)

(iFR.py:519771): Gtk-CRITICAL **: 20:20:43.053: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
Traceback (most recent call last):
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 452, in <module>
    iFR(None, title='iFR')
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 371, in __init__
    self.InitUI()
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 424, in InitUI
    self.PopulateAvailableProgrammers()
  File "/home/jakob/Downloads/esp32-serial-bios/iFR/iFR.py", line 429, in PopulateAvailableProgrammers
    options_start = output_lines.index(b'Valid choices are:\n')
ValueError: b'Valid choices are:\n' is not in list
```

**Comment by Jazzzny** [comment]
I fixed the error incorrectly, please try the updated commit

**Comment by feja111** [comment]
It seems to be working now.
Thanks a lot.
